module.exports = {
  name: 'lingo',
  features: [
    {
      tcid: '0',
      name: '@lingo-banner-display',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-lingodisplay',
    },
    {
      tcid: '1',
      name: '@lingo-banner-display-cancle',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-banner-rejection',
    },
    {
      tcid: '2',
      name: '@lingo-banner-display-accept',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-banner-acceptance',
      url: 'https://business.stage.adobe.com/in/products/creativecloud-business.html',
    },
    {
      tcid: '3',
      name: '@lingo-supported-lang-directurl',
      path: '/uk/',
      tags: '@cc @lingo-feature-cc @cc-lingo-supported-lang-directurl',
      url: 'https://business.stage.adobe.com/uk/',
    },
    {
      tcid: '4',
      name: '@lingo-support-lang-redierction',
      path: '/nz',
      tags: '@cc @lingo-feature-cc @cc-lingo-supported-lang-redirection',
      url: 'https://business.stage.adobe.com',
    },
    {
      tcid: '5',
      name: '@lingo-banner-no-geomodel',
      path: '/creativecloud?georouting=off',
      tags: '@cc @lingo-feature-cc @cc-no-geomodel-display',
    },
    {
      tcid: '6',
      name: '@lingo-language-picker',
      path: '/industries/financial-services.html',
      tags: '@cc @lingo-feature-cc @cc-language-picker-footer',
    },
    {
      tcid: '7',
      name: '@lingo-language-select-kr',
      path: '/industries/financial-services.html',
      tags: '@cc @lingo-feature-cc @cc-language-select-kr',
      url: 'https://business.stage.adobe.com/kr/industries/financial-services.html',
    },
    {
      tcid: '8',
      name: '@lingo-banner-not-to-be-displayed',
      path: '/fr/solutions/content-management.html?akamaiLocale=fr',
      tags: '@cc @lingo-feature-cc @cc-no-banner-display',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=fr',
    },
    {
      tcid: '9',
      name: '@display-lingo-banner-in-german-language',
      path: '/fr/solutions/content-management.html?akamaiLocale=de',
      tags: '@cc @lingo-feature-cc @cc-lingo-de-banner',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=de',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
    },
    {
      tcid: '10',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/customer-success-stories.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-no-banner-no-cookies',
      url: 'https://business.stage.adobe.com/it/customer-success-stories.html?akamaiLocale=ch',
    },
    {
      tcid: '11',
      name: '@display-lingo-banner-in-US',
      path: '/uk/solutions/content-management.html?akamaiLocale=ca',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-US',
      url: 'https://business.stage.adobe.com/uk/solutions/content-management.html?akamaiLocale=ca',
      bannerLink: 'https://business.stage.adobe.com/solutions/content-management.html',
    },
    {
      tcid: '12',
      name: '@display-lingo-banner-in-german-language-for-jp',
      path: '/jp/customer-success-stories.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-DE-forJP',
      url: 'https://business.stage.adobe.com/jp/customer-success-stories.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/customer-success-stories.html',
    },
    {
      tcid: '13',
      name: '@no-lingo-banner',
      path:
        '/br/resources/videos/adobe-journey-optimizer-video-about-the-solution/thank-you.html?akamaiLocale=DE',
      tags: '@cc @lingo-feature-cc @cc-no-banner-display',
      url:
        'https://business.stage.adobe.com/br/resources/videos/'
        + 'adobe-journey-optimizer-video-about-the-solution/thank-you.html?akamaiLocale=DE',
    },
    {
      tcid: '14',
      name: '@display-lingo-banner-in-French-language-for-IT',
      path: '/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-FR-forIT',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
      changeRegionURL: 'https://business.stage.adobe.com/fr/solutions/content-management.html',
      redirectURL: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=ch',
      expectedURl: 'https://business.stage.adobe.com/fr/solutions/content-management.html',
    },
    {
      tcid: '15',
      name: '@display-lingo-banner-in-Italian-language-for-DE',
      path: '/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-IT-forDE',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
      changeRegionURL: 'https://business.stage.adobe.com/it/solutions/content-management.html',
      redirectURL: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=ch',
      expectedURl: 'https://business.stage.adobe.com/it/solutions/content-management.html',
    },
  ],
};
