module.exports = {
  name: 'lingo',
  features: [
    {
      tcid: '0',
      name: '@lingo-banner-display',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-lingodisplay',
    },
    {
      tcid: '1',
      name: '@lingo-banner-display-cancle',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-banner-rejection',
    },
    {
      tcid: '2',
      name: '@lingo-banner-display-accept',
      path: '/products/creativecloud-business.html',
      tags: '@cc @lingo-feature-cc @cc-banner-acceptance',
      url: 'https://business.stage.adobe.com/in/products/creativecloud-business.html',
    },
    {
      tcid: '3',
      name: '@lingo-supported-lang-directurl',
      path: '/uk/',
      tags: '@cc @lingo-feature-cc @cc-lingo-supported-lang-directurl',
      url: 'https://business.stage.adobe.com/uk/',
    },
    {
      tcid: '4',
      name: '@lingo-support-lang-redierction',
      path: '/nz',
      tags: '@cc @lingo-feature-cc @cc-lingo-supported-lang-redirection',
      url: 'https://business.stage.adobe.com',
    },
    {
      tcid: '5',
      name: '@lingo-banner-no-geomodel',
      path: '/creativecloud?georouting=off',
      tags: '@cc @lingo-feature-cc @cc-no-geomodel-display',
    },
    {
      tcid: '6',
      name: '@lingo-language-picker',
      path: '/industries/financial-services.html',
      tags: '@cc @lingo-feature-cc @cc-language-picker-footer',
    },
    {
      tcid: '7',
      name: '@lingo-language-select-kr',
      path: '/industries/financial-services.html',
      tags: '@cc @lingo-feature-cc @cc-language-select-kr',
      url: 'https://business.stage.adobe.com/kr/industries/financial-services.html',
    },
    {
      tcid: '8',
      name: '@lingo-banner-not-to-be-displayed',
      path: '/fr/solutions/content-management.html?akamaiLocale=fr',
      tags: '@cc @lingo-feature-cc @cc-no-banner-display',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=fr',
    },
    {
      tcid: '9',
      name: '@display-lingo-banner-in-german-language',
      path: '/fr/solutions/content-management.html?akamaiLocale=de',
      tags: '@cc @lingo-feature-cc @cc-lingo-de-banner',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=de',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
    },
    {
      tcid: '10',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/customer-success-stories.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-no-banner-no-cookies',
      url: 'https://business.stage.adobe.com/it/customer-success-stories.html?akamaiLocale=ch',
    },
    {
      tcid: '11',
      name: '@display-lingo-banner-in-US',
      path: '/uk/solutions/content-management.html?akamaiLocale=ca',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-US',
      url: 'https://business.stage.adobe.com/uk/solutions/content-management.html?akamaiLocale=ca',
      bannerLink: 'https://business.stage.adobe.com/solutions/content-management.html',
    },
    {
      tcid: '12',
      name: '@display-lingo-banner-in-german-language-for-jp',
      path: '/jp/customer-success-stories.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-DE-forJP',
      url: 'https://business.stage.adobe.com/jp/customer-success-stories.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/customer-success-stories.html',
    },
    {
      tcid: '13',
      name: '@no-lingo-banner',
      path:
        '/br/resources/videos/adobe-journey-optimizer-video-about-the-solution/thank-you.html?akamaiLocale=DE',
      tags: '@cc @lingo-feature-cc @cc-no-banner-display',
      url:
        'https://business.stage.adobe.com/br/resources/videos/'
        + 'adobe-journey-optimizer-video-about-the-solution/thank-you.html?akamaiLocale=DE',
    },
    {
      tcid: '14',
      name: '@display-lingo-banner-in-French-language-for-IT',
      path: '/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-FR-forIT',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
      changeRegionURL: 'https://business.stage.adobe.com/fr/solutions/content-management.html',
      redirectURL: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=ch',
      expectedURl: 'https://business.stage.adobe.com/fr/solutions/content-management.html',
    },
    {
      tcid: '15',
      name: '@display-lingo-banner-in-Italian-language-for-DE',
      path: '/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @lingo-feature-cc @cc-lingo-banner-IT-forDE',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ch',
      bannerLink: 'https://business.stage.adobe.com/de/solutions/content-management.html',
      changeRegionURL: 'https://business.stage.adobe.com/it/solutions/content-management.html',
      redirectURL: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=ch',
      expectedURl: 'https://business.stage.adobe.com/it/solutions/content-management.html',
    },
    {
      tcid: '16',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ae',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ae',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ae',
    },
    {
      tcid: '17',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=af',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-af',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=af',
    },
    {
      tcid: '18',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ag',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ag',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ag',
    },
    {
      tcid: '19',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ai',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ai',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ai',
    },
    {
      tcid: '20',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=al',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-al',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=al',
    },
    {
      tcid: '21',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=am',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-am',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=am',
    },
    {
      tcid: '22',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=aq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-aq',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=aq',
    },
    {
      tcid: '23',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=as',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-as',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=as',
    },
    {
      tcid: '24',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=aw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-aw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=aw',
    },
    {
      tcid: '25',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=az',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-az',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=az',
    },
    {
      tcid: '26',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ba',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ba',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ba',
    },
    {
      tcid: '27',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bb',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bb',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bb',
    },
    {
      tcid: '28',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bd',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bd',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bd',
    },
    {
      tcid: '29',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=be',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-be',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=be',
    },
    {
      tcid: '30',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bg',
    },
    {
      tcid: '31',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bh',
    },
    {
      tcid: '32',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bm',
    },
    {
      tcid: '33',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bn',
    },
    {
      tcid: '34',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bq',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bq',
    },
    {
      tcid: '35',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bs',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bs',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bs',
    },
    {
      tcid: '36',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bt',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bt',
    },
    {
      tcid: '37',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bv',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bv',
    },
    {
      tcid: '38',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bw',
    },
    {
      tcid: '39',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=by',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-by',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=by',
    },
    {
      tcid: '40',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=bz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-bz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=bz',
    },
    {
      tcid: '41',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ca',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ca',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ca',
    },
    {
      tcid: '42',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cc',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cc',
    },
    {
      tcid: '43',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ck',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ck',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ck',
    },
    {
      tcid: '44',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cn',
    },
    {
      tcid: '45',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cw',
    },
    {
      tcid: '46',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cx',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cx',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cx',
    },
    {
      tcid: '47',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cy',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cy',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cy',
    },
    {
      tcid: '48',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=cz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-cz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=cz',
    },
    {
      tcid: '49',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=dk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-dk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=dk',
    },
    {
      tcid: '50',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=dm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-dm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=dm',
    },
    {
      tcid: '51',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ee',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ee',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ee',
    },
    {
      tcid: '52',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=eg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-eg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=eg',
    },
    {
      tcid: '53',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=eh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-eh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=eh',
    },
    {
      tcid: '54',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=er',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-er',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=er',
    },
    {
      tcid: '55',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=et',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-et',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=et',
    },
    {
      tcid: '56',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=fi',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fi',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=fi',
    },
    {
      tcid: '57',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=fj',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fj',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=fj',
    },
    {
      tcid: '58',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=fk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=fk',
    },
    {
      tcid: '59',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=fm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=fm',
    },
    {
      tcid: '60',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=fo',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fo',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=fo',
    },
    {
      tcid: '61',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gd',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gd',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gd',
    },
    {
      tcid: '62',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ge',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ge',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ge',
    },
    {
      tcid: '63',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gg',
    },
    {
      tcid: '64',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gh',
    },
    {
      tcid: '65',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gi',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gi',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gi',
    },
    {
      tcid: '66',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gl',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gl',
    },
    {
      tcid: '67',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gm',
    },
    {
      tcid: '68',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gr',
    },
    {
      tcid: '69',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gs',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gs',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gs',
    },
    {
      tcid: '70',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gu',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gu',
    },
    {
      tcid: '71',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=gy',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-gy',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gy',
    },
    {
      tcid: '72',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=hk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-hk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=hk',
    },
    {
      tcid: '73',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=hm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-hm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=hm',
    },
    {
      tcid: '74',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=hr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-hr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=hr',
    },
    {
      tcid: '75',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=hu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-hu',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=hu',
    },
    {
      tcid: '76',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=id',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-id',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=id',
    },
    {
      tcid: '77',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ie',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ie',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ie',
    },
    {
      tcid: '78',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=il',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-il',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=il',
    },
    {
      tcid: '79',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=im',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-im',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=im',
    },
    {
      tcid: '80',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=io',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-io',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=io',
    },
    {
      tcid: '81',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=iq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-iq',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=iq',
    },
    {
      tcid: '82',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ir',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ir',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ir',
    },
    {
      tcid: '83',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=is',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-is',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=is',
    },
    {
      tcid: '84',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=je',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-je',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=je',
    },
    {
      tcid: '85',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=jm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-jm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=jm',
    },
    {
      tcid: '86',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=jo',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-jo',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=jo',
    },
    {
      tcid: '87',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ke',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ke',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ke',
    },
    {
      tcid: '88',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kg',
    },
    {
      tcid: '89',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kh',
    },
    {
      tcid: '90',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ki',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ki',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ki',
    },
    {
      tcid: '91',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kn',
    },
    {
      tcid: '92',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kp',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kp',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kp',
    },
    {
      tcid: '93',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kw',
    },
    {
      tcid: '94',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ky',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ky',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ky',
    },
    {
      tcid: '95',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=kz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kz',
    },
    {
      tcid: '96',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=la',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-la',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=la',
    },
    {
      tcid: '97',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lb',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lb',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lb',
    },
    {
      tcid: '98',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lc',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lc',
    },
    {
      tcid: '99',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lk',
    },
    {
      tcid: '100',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lr',
    },
    {
      tcid: '101',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ls',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ls',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ls',
    },
    {
      tcid: '102',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lt',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lt',
    },
    {
      tcid: '103',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lu',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lu',
    },
    {
      tcid: '104',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=lv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-lv',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=lv',
    },
    {
      tcid: '105',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ly',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ly',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ly',
    },
    {
      tcid: '106',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ma',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ma',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ma',
    },
    {
      tcid: '107',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=md',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-md',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=md',
    },
    {
      tcid: '108',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=me',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-me',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=me',
    },
    {
      tcid: '109',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mh',
    },
    {
      tcid: '110',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mk',
    },
    {
      tcid: '111',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mm',
    },
    {
      tcid: '112',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mn',
    },
    {
      tcid: '113',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mp',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mp',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mp',
    },
    {
      tcid: '114',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ms',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ms',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ms',
    },
    {
      tcid: '115',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mt',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mt',
    },
    {
      tcid: '116',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mv',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mv',
    },
    {
      tcid: '117',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=mw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-mw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=mw',
    },
    {
      tcid: '118',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=my',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-my',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=my',
    },
    {
      tcid: '119',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=na',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-na',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=na',
    },
    {
      tcid: '120',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=nf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-nf',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=nf',
    },
    {
      tcid: '121',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ng',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ng',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ng',
    },
    {
      tcid: '122',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ni',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ni',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ni',
    },
    {
      tcid: '123',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=nl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-nl',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=nl',
    },
    {
      tcid: '124',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=no',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-no',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=no',
    },
    {
      tcid: '125',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=np',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-np',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=np',
    },
    {
      tcid: '126',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=nr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-nr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=nr',
    },
    {
      tcid: '127',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=nu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-nu',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=nu',
    },
    {
      tcid: '128',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=nz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-nz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=nz',
    },
    {
      tcid: '129',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=om',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-om',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=om',
    },
    {
      tcid: '130',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=pg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=pg',
    },
    {
      tcid: '131',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ph',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ph',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ph',
    },
    {
      tcid: '132',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=pk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=pk',
    },
    {
      tcid: '133',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=pl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pl',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=pl',
    },
    {
      tcid: '134',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=pn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=pn',
    },
    {
      tcid: '135',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ps',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ps',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ps',
    },
    {
      tcid: '136',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=pw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=pw',
    },
    {
      tcid: '137',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=qa',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-qa',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=qa',
    },
    {
      tcid: '138',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ro',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ro',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ro',
    },
    {
      tcid: '139',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=rs',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-rs',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=rs',
    },
    {
      tcid: '140',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ru',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ru',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ru',
    },
    {
      tcid: '141',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sa',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sa',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sa',
    },
    {
      tcid: '142',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sb',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sb',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sb',
    },
    {
      tcid: '143',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sd',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sd',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sd',
    },
    {
      tcid: '144',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=se',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-se',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=se',
    },
    {
      tcid: '145',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sg',
    },
    {
      tcid: '146',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sh',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sh',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sh',
    },
    {
      tcid: '147',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=si',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-si',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=si',
    },
    {
      tcid: '148',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sj',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sj',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sj',
    },
    {
      tcid: '149',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sk',
    },
    {
      tcid: '150',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sl',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sl',
    },
    {
      tcid: '151',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=so',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-so',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=so',
    },
    {
      tcid: '152',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sr',
    },
    {
      tcid: '153',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ss',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ss',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ss',
    },
    {
      tcid: '154',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sx',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sx',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sx',
    },
    {
      tcid: '155',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sy',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sy',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sy',
    },
    {
      tcid: '156',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=sz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-sz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=sz',
    },
    {
      tcid: '157',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tc',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tc',
    },
    {
      tcid: '158',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tf',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tf',
    },
    {
      tcid: '159',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=th',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-th',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=th',
    },
    {
      tcid: '160',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tj',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tj',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tj',
    },
    {
      tcid: '161',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tk',
    },
    {
      tcid: '162',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tm',
    },
    {
      tcid: '163',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=to',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-to',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=to',
    },
    {
      tcid: '164',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tr',
    },
    {
      tcid: '165',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tt',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tt',
    },
    {
      tcid: '166',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tv',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tv',
    },
    {
      tcid: '167',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tw',
    },
    {
      tcid: '168',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=tz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-tz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=tz',
    },
    {
      tcid: '169',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ua',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ua',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ua',
    },
    {
      tcid: '170',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ug',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ug',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ug',
    },
    {
      tcid: '171',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=um',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-um',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=um',
    },
    {
      tcid: '172',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=uz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-uz',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=uz',
    },
    {
      tcid: '173',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=vc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-vc',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=vc',
    },
    {
      tcid: '174',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=vg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-vg',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=vg',
    },
    {
      tcid: '175',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=vi',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-vi',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=vi',
    },
    {
      tcid: '176',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=vn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-vn',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=vn',
    },
    {
      tcid: '177',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ws',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ws',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ws',
    },
    {
      tcid: '178',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=xk',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-xk',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=xk',
    },
    {
      tcid: '179',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=ye',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ye',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=ye',
    },
    {
      tcid: '180',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=za',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-za',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=za',
    },
    {
      tcid: '181',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=zm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-zm',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=zm',
    },
    {
      tcid: '182',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/solutions/content-management.html?akamaiLocale=zw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-zw',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=zw',
    },
    {
      tcid: '183',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/uk/solutions/content-management.html?akamaiLocale=gb',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-uk-gb',
      url: 'https://business.stage.adobe.com/uk/solutions/content-management.html?akamaiLocale=gb',
    },
    {
      tcid: '184',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/au/solutions/content-management.html?akamaiLocale=au',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-au-au',
      url: 'https://business.stage.adobe.com/au/solutions/content-management.html?akamaiLocale=au',
    },
    {
      tcid: '185',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/in/solutions/content-management.html?akamaiLocale=in',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-in-in',
      url: 'https://business.stage.adobe.com/in/solutions/content-management.html?akamaiLocale=in',
    },
    {
      tcid: '186',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/jp/solutions/content-management.html?akamaiLocale=ja',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-ja-jp',
      url: 'https://business.stage.adobe.com/jp/solutions/content-management.html?akamaiLocale=ja',
    },
    {
      tcid: '186',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/kr/solutions/content-management.html?akamaiLocale=ko',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-kr-ko',
      url: 'https://business.stage.adobe.com/kr/solutions/content-management.html?akamaiLocale=ko',
    },
    {
      tcid: '187',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=fr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-fr',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=fr',
    },
    {
      tcid: '188',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=es',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-es',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=es',
    },
    {
      tcid: '189',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/solutions/content-management.html?akamaiLocale=it',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-it-it',
      url: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=it',
    },
    {
      tcid: '190',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=pt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-pt',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=pt',
    },
    {
      tcid: '191',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/de/solutions/content-management.html?akamaiLocale=de',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-de-de',
      url: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=de',
    },
    {
      tcid: '192',
      name: '@display-lingo-us-banner',
      path: '/fr/solutions/content-management.html?akamaiLocale=be',
      tags: '@cc @cc-lingo @cc-us-lingo-banner-display-fr-be',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=be',
      expectedURl: 'https://business.stage.adobe.com/solutions/content-management.html',
    },
    {
      tcid: '193',
      name: '@display-lingo-us-banner',
      path: '/fr/solutions/content-management.html?akamaiLocale=lu',
      tags: '@cc @cc-lingo @cc-us-lingo-banner-display-fr-lu',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=lu',
      expectedURl: 'https://business.stage.adobe.com/solutions/content-management.html',
    },
    {
      tcid: '194',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ch',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ch',
    },
    {
      tcid: '195',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mc',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mc',
    },
    {
      tcid: '196',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ad',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ad',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ad',
    },
    {
      tcid: '197',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=dz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-dz',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=dz',
    },
    {
      tcid: '198',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=bj',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-bj',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=bj',
    },
    {
      tcid: '199',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=bf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-bf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=bf',
    },
    {
      tcid: '200',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=bi',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-bi',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=bi',
    },
    {
      tcid: '201',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=cm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-cm',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=cm',
    },
    {
      tcid: '202',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=cf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-cf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=cf',
    },
    {
      tcid: '203',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=td',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-td',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=td',
    },
    {
      tcid: '204',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=km',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-km',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=km',
    },
    {
      tcid: '205',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=cg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-cg',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=cg',
    },
    {
      tcid: '206',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=cd',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-cd',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=cd',
    },
    {
      tcid: '207',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ci',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ci',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ci',
    },
    {
      tcid: '208',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=dj',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-dj',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=dj',
    },
    {
      tcid: '209',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=gq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-gq',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=gq',
    },
    {
      tcid: '210',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ga',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ga',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ga',
    },
    {
      tcid: '211',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=gn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-gn',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=gn',
    },
    {
      tcid: '212',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=gw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-gw',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=gw',
    },
    {
      tcid: '213',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mg',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mg',
    },
    {
      tcid: '214',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ml',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ml',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ml',
    },
    {
      tcid: '215',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mr',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mr',
    },
    {
      tcid: '216',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mu',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mu',
    },
    {
      tcid: '217',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=yt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-yt',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=yt',
    },
    {
      tcid: '218',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ne',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ne',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ne',
    },
    {
      tcid: '219',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=re',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-re',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=re',
    },
    {
      tcid: '220',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=rw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-rw',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=rw',
    },
    {
      tcid: '221',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=sn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-sn',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=sn',
    },
    {
      tcid: '222',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=sc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-sc',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=sc',
    },
    {
      tcid: '223',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=tg',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-tg',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=tg',
    },
    {
      tcid: '224',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=tn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-tn',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=tn',
    },
    {
      tcid: '225',
      name: '@display-lingo-us-banner',
      path: '/fr/solutions/content-management.html?akamaiLocale=ca',
      tags: '@cc @cc-lingo @cc-us-lingo-banner-display-fr-ca',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ca',
      expectedURl: 'https://business.stage.adobe.com/solutions/content-management.html',
    },
    {
      tcid: '226',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=gp',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-gp',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=gp',
    },
    {
      tcid: '227',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mq',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mq',
    },
    {
      tcid: '228',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=gf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-gf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=gf',
    },
    {
      tcid: '229',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=pm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-pm',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=pm',
    },
    {
      tcid: '230',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=bl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-bl',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=bl',
    },
    {
      tcid: '231',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=mf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-mf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=mf',
    },
    {
      tcid: '232',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=ht',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-ht',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=ht',
    },
    {
      tcid: '233',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=nc',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-nc',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=nc',
    },
    {
      tcid: '234',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=pf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-pf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=pf',
    },
    {
      tcid: '235',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=wf',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-wf',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=wf',
    },
    {
      tcid: '236',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/fr/solutions/content-management.html?akamaiLocale=vu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-fr-vu',
      url: 'https://business.stage.adobe.com/fr/solutions/content-management.html?akamaiLocale=vu',
    },
    {
      tcid: '237',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/de/solutions/content-management.html?akamaiLocale=at',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-de-at',
      url: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=at',
    },
    {
      tcid: '238',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/de/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-de-ch',
      url: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=ch',
    },
    {
      tcid: '239',
      name: '@display-lingo-us-banner',
      path: '/de/solutions/content-management.html?akamaiLocale=lu',
      tags: '@cc @cc-lingo @cc-us-lingo-banner-display-de-lu',
      url: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=lu',
    },
    {
      tcid: '240',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/de/solutions/content-management.html?akamaiLocale=li',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-de-li',
      url: 'https://business.stage.adobe.com/de/solutions/content-management.html?akamaiLocale=li',
    },
    {
      tcid: '241',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=ar',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-ar',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=ar',
    },
    {
      tcid: '242',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=bo',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-bo',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=bo',
    },
    {
      tcid: '243',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=cl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-cl',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=cl',
    },
    {
      tcid: '244',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=co',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-co',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=co',
    },
    {
      tcid: '245',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=cr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-cr',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=cr',
    },
    {
      tcid: '246',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=cu',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-cu',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=cu',
    },
    {
      tcid: '247',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=do',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-do',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=do',
    },
    {
      tcid: '248',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=ec',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-ec',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=ec',
    },
    {
      tcid: '249',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=sv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-sv',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=sv',
    },
    {
      tcid: '250',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=gt',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-gt',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=gt',
    },
    {
      tcid: '251',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=hn',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-hn',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=hn',
    },
    {
      tcid: '252',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=mx',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-mx',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=mx',
    },
    {
      tcid: '253',
      name: '@display-lingo-us-banner',
      path: '/es/solutions/content-management.html?akamaiLocale=ni',
      tags: '@cc @cc-lingo @cc-us-lingo-banner-display-es-ni',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=ni',
    },
    {
      tcid: '254',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=pa',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-pa',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=pa',
    },
    {
      tcid: '255',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=py',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-py',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=py',
    },
    {
      tcid: '256',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=pe',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-pe',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=pe',
    },
    {
      tcid: '257',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=pr',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-pr',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=pr',
    },
    {
      tcid: '258',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=uy',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-uy',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=uy',
    },
    {
      tcid: '259',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=ve',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-ve',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=ve',
    },
    {
      tcid: '260',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/es/solutions/content-management.html?akamaiLocale=gq',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-es-gq',
      url: 'https://business.stage.adobe.com/es/solutions/content-management.html?akamaiLocale=gq',
    },
    {
      tcid: '261',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/solutions/content-management.html?akamaiLocale=ch',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-it-ch',
      url: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=ch',
    },
    {
      tcid: '262',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/solutions/content-management.html?akamaiLocale=sm',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-it-sm',
      url: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=sm',
    },
    {
      tcid: '263',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/it/solutions/content-management.html?akamaiLocale=va',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-it-va',
      url: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=va',
    },
    {
      tcid: '264',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=br',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-br',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=br',
    },
    {
      tcid: '265',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=ao',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-ao',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=ao',
    },
    {
      tcid: '266',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=cv',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-cv',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=cv',
    },
    {
      tcid: '267',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=gw',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-gw',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=gw',
    },
    {
      tcid: '268',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=mz',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-mz',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=mz',
    },
    {
      tcid: '269',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=st',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-st',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=st',
    },
    {
      tcid: '270',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=tl',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-tl',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=tl',
    },
    {
      tcid: '271',
      name: '@no-lingo-banner-and-no-cookies',
      path: '/pt/solutions/content-management.html?akamaiLocale=mo',
      tags: '@cc @cc-lingo @cc-no-lingo-banner-display-pt-mo',
      url: 'https://business.stage.adobe.com/pt/solutions/content-management.html?akamaiLocale=mo',
    },
    {
      tcid: '272',
      name: '@display-lingo-banner-in-pt-language-for-it',
      path: '/it/products/experience-manager/assets.html?akamaiLocale=pt',
      tags: '@cc @cc-lingo @cc-lingodisplay-it-pt',
      url: 'https://business.stage.adobe.com/it/products/experience-manager/assets.html?akamaiLocale=pt',
      bannerLink: 'https://business.stage.adobe.com/pt/products/experience-manager/assets.html',
    },
    {
      tcid: '273',
      name: '@display-lingo-banner-fr-lan-for-UK-CA',
      path: '/uk/request-consultation.html?akamaiLocale=ca&mep=off',
      tags: '@cc @cc-lingo @cc-lingo-display-fr-for-uk/ca',
      url: 'https://business.stage.adobe.com/uk/request-consultation.html?akamaiLocale=ca&mep=off',
      bannerLink: 'https://business.stage.adobe.com/request-consultation.html',
      changeRegionURL: 'https://business.stage.adobe.com/fr/request-consultation.html?akamaiLocale=ca&mep=off',
      redirectURL: 'https://business.stage.adobe.com/uk/request-consultation.html?akamaiLocale=ca&mep=off',
      expectedURl: 'https://business.stage.adobe.com/fr/request-consultation.html',
    },
    {
      tcid: '274',
      name: '@display-lingo-banner-jp-language-for-it',
      path: '/it/solutions/content-management.html?akamaiLocale=jp',
      tags: '@cc @cc-lingo @cc-lingodisplay-jp-it',
      url: 'https://business.stage.adobe.com/it/solutions/content-management.html?akamaiLocale=jp',
      bannerLink: 'https://business.stage.adobe.com/jp/solutions/content-management.html',
    },
    {
      tcid: '275',
      name: '@display-lingo-banner-uk-language-for-gb',
      path: '/solutions/content-management.html?akamaiLocale=gb',
      tags: '@cc @cc-lingo @cc-lingodisplay-us-gb',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=gb',
      bannerLink: 'https://business.stage.adobe.com/uk/solutions/content-management.html',
    },
    {
      tcid: '276',
      name: '@display-lingo-banner-au-language-for-au',
      path: '/solutions/content-management.html?akamaiLocale=au',
      tags: '@cc @cc-lingo @cc-lingodisplay-us-au',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=au',
      bannerLink: 'https://business.stage.adobe.com/au/solutions/content-management.html',
    },
    {
      tcid: '277',
      name: '@display-lingo-banner-es-language-for-es',
      path: '/solutions/content-management.html?akamaiLocale=es',
      tags: '@cc @cc-lingo @cc-lingodisplay-us-es',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=es',
      bannerLink: 'https://business.stage.adobe.com/es/solutions/content-management.html',
    },
    {
      tcid: '278',
      name: '@display-lingo-banner-kr-language-for-kr',
      path: '/solutions/content-management.html?akamaiLocale=kr',
      tags: '@cc @cc-lingo @cc-lingodisplay-us-kr',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=kr',
      bannerLink: 'https://business.stage.adobe.com/kr/solutions/content-management.html',
    },
    {
      tcid: '279',
      name: '@display-lingo-banner-it-language-for-it',
      path: '/solutions/content-management.html?akamaiLocale=it',
      tags: '@cc @cc-lingo @cc-lingodisplay-us-it',
      url: 'https://business.stage.adobe.com/solutions/content-management.html?akamaiLocale=it',
      bannerLink: 'https://business.stage.adobe.com/it/solutions/content-management.html',
    },
  ],
};
